// CORS helper for browser clients (the future web UI calls these directly).
// NOTE: `server/` and `src/` in this directory are GENERATED by
// `npm run server:sync-shared` — do not edit them here. This file is
// handwritten and preserved by the sync script.

export const corsHeaders: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

export function jsonWithCors(body: unknown, status: number): Response {
  return Response.json(body, { status, headers: corsHeaders });
}

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}
