// Supabase-backed Db adapter for Edge Functions (Deno-only: not imported
// by Vitest). Maps snake_case rows to the server core's camelCase types.
// NOTE: `server/` and `src/` in this directory are GENERATED by
// `npm run server:sync-shared` — do not edit them here. This file is
// handwritten and preserved by the sync script.
import type { SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.44.4';
import type {
  BoardSet,
  Db,
  DraftSet,
  GameRow,
  RoomRow,
  SeatRow,
  Tile,
} from './server/types.ts';

interface RoomRecord {
  code: string;
  host_name: string;
  is_public: boolean;
  preset: string;
  phase: string;
  winner_seat: number | null;
  created_at: number;
  last_activity_at: number;
}

interface SeatRecord {
  room_code: string;
  seat: number;
  name: string;
  connected: boolean;
  hand: Tile[];
  has_melded: boolean;
}

interface GameRecord {
  room_code: string;
  board: BoardSet[];
  pool: Tile[];
  turn_seat: number;
  draft: DraftSet[];
}

function toRoom(r: RoomRecord): RoomRow {
  return {
    code: r.code,
    hostName: r.host_name,
    isPublic: r.is_public,
    preset: r.preset as RoomRow['preset'],
    phase: r.phase as RoomRow['phase'],
    winnerSeat: r.winner_seat,
    createdAt: r.created_at,
    lastActivityAt: r.last_activity_at,
  };
}

function toSeat(s: SeatRecord): SeatRow {
  return {
    roomCode: s.room_code,
    seat: s.seat,
    name: s.name,
    connected: s.connected,
    hand: s.hand,
    hasMelded: s.has_melded,
  };
}

function toGame(g: GameRecord): GameRow {
  return { roomCode: g.room_code, board: g.board, pool: g.pool, turnSeat: g.turn_seat, draft: g.draft ?? [] };
}

function must<T>(res: { data: T; error: unknown }, what: string): NonNullable<T> {
  if (res.error) throw new Error(`supabase ${what}: ${JSON.stringify(res.error)}`);
  return res.data as NonNullable<T>;
}

/** Db backed by Supabase tables; the function uses the service role. */
export function makeSupabaseDb(client: SupabaseClient): Db {
  return {
    async insertRoom(room) {
      must(
        await client.from('rooms').insert({
          code: room.code,
          host_name: room.hostName,
          is_public: room.isPublic,
          preset: room.preset,
          phase: room.phase,
          winner_seat: room.winnerSeat,
          created_at: room.createdAt,
          last_activity_at: room.lastActivityAt,
        }),
        'insertRoom',
      );
    },
    async getRoom(code) {
      const res = must(await client.from('rooms').select('*').eq('code', code).maybeSingle(), 'getRoom');
      return res ? toRoom(res as RoomRecord) : null;
    },
    async updateRoom(room) {
      must(
        await client
          .from('rooms')
          .update({
            host_name: room.hostName,
            is_public: room.isPublic,
            preset: room.preset,
            phase: room.phase,
            winner_seat: room.winnerSeat,
            last_activity_at: room.lastActivityAt,
          })
          .eq('code', room.code),
        'updateRoom',
      );
    },
    async deleteRoom(code) {
      must(await client.from('rooms').delete().eq('code', code), 'deleteRoom');
    },
    async listPublicLobbyRooms() {
      const rows = must(await client.from('rooms').select('*').eq('is_public', true), 'listPublicLobbyRooms');
      return (rows as RoomRecord[]).map(toRoom);
    },
    async listAllRooms() {
      const rows = must(await client.from('rooms').select('*'), 'listAllRooms');
      return (rows as RoomRecord[]).map(toRoom);
    },
    async insertSeat(seat) {
      must(
        await client.from('seats').insert({
          room_code: seat.roomCode,
          seat: seat.seat,
          name: seat.name,
          connected: seat.connected,
          hand: seat.hand,
          has_melded: seat.hasMelded,
        }),
        'insertSeat',
      );
    },
    async getSeat(roomCode, seat) {
      const res = must(
        await client.from('seats').select('*').eq('room_code', roomCode).eq('seat', seat).maybeSingle(),
        'getSeat',
      );
      return res ? toSeat(res as SeatRecord) : null;
    },
    async listSeats(roomCode) {
      const rows = must(await client.from('seats').select('*').eq('room_code', roomCode), 'listSeats');
      return (rows as SeatRecord[]).map(toSeat);
    },
    async updateSeat(seat) {
      must(
        await client
          .from('seats')
          .update({ name: seat.name, connected: seat.connected, hand: seat.hand, has_melded: seat.hasMelded })
          .eq('room_code', seat.roomCode)
          .eq('seat', seat.seat),
        'updateSeat',
      );
    },
    async deleteSeats(roomCode) {
      must(await client.from('seats').delete().eq('room_code', roomCode), 'deleteSeats');
    },
    async getGame(roomCode) {
      const res = must(await client.from('games').select('*').eq('room_code', roomCode).maybeSingle(), 'getGame');
      return res ? toGame(res as GameRecord) : null;
    },
    async upsertGame(game) {
      must(
        await client.from('games').upsert(
          { room_code: game.roomCode, board: game.board, pool: game.pool, turn_seat: game.turnSeat, draft: game.draft },
          { onConflict: 'room_code' },
        ),
        'upsertGame',
      );
    },
    async deleteGame(roomCode) {
      must(await client.from('games').delete().eq('room_code', roomCode), 'deleteGame');
    },
  };
}
